/**
 * SKINET.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccessTokenResponse { 
    readonly tokenType?: string | null;
    accessToken: string | null;
    expiresIn: number;
    refreshToken: string | null;
}

