/**
 * SKINET.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Addresss { 
    id?: number;
    line1: string | null;
    line2?: string | null;
    city: string | null;
    state: string | null;
    postalCode: string | null;
    country: string | null;
}

