/**
 * SKINET.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateProductDto { 
    name: string;
    description: string;
    price?: number;
    pictureUrl: string;
    type: string;
    quantityInStock?: number;
    brand: string;
}

