/**
 * SKINET.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Deliverymethod ={ 
    id: number;
    shortName: string;
    deliveryTime: string;
    description: string;
    price: number;
}

