/**
 * SKINET.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatus } from './orderStatus';
import { Deliverymethod } from './deliverymethod';
import { PaymentSummary } from './paymentSummary';
import { OrderItem } from './orderItem';
import { ShippingAddress } from './shippingAddress';


export interface Order { 
    orderDate?: string;
    buyerEmail: string ;
    shippingAddress?: ShippingAddress;
    deliverymethod?: Deliverymethod;
    payment?: PaymentSummary;
    orderItems?: OrderItem[] | null;
    subtotal?: number;
    status?: OrderStatus;
    paymentId: string | null;
}


