/**
 * SKINET.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItemDto } from './orderItemDto';
import { PaymentSummary } from './paymentSummary';
import { ShippingAddress } from './shippingAddress';


export interface OrderDTO { 
    id?: number;
    orderDate?: string;
    buyerEmail: string | null;
    shippingAddress: ShippingAddress;
    Deliverymethod: string | null;
    payment: PaymentSummary;
    orderItems?:OrderItemDto[];
    total?: number;
    shippingPrice?: number;
    status: string | null;
    paymentId: string | null;
}

