/**
 * SKINET.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderItemDto { 
    productId?: number;
    productName: string | null;
    price?: number;
    pictureUrl: string | null;
    quantity?: number;
}

