/**
 * SKINET.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface Product {
  id: number;
  name: string | null;
  description: string | null;
  price: number;
  pictureUrl: string | null;
  type: string | null;
  quantityInStock?: number;
  brand: string | null;
}
