/**
 * SKINET.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface ProductPagination { 
    pageIndex?: number;
    pageSize?: number;
    count?: number;
    data?: Array<Product>;
}

