/**
 * SKINET.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from "./addressDto";



export interface User { 
 firstName: string| null;
  lastName: string | null;
  email: string | null;
  password: string | null;
}

