/**
 * SKINET.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartItem } from './cartItem';
import { nanoid } from "nanoid"

export class ShopCart implements CartType { 
  id = nanoid();
  items: CartItem[]=[];
}

export interface CartType  {
  id: string;
  items: CartItem[]
}
