export * from './account.service';
import { AccountService } from './account.service';
export * from './cart.service';
import { CartService } from './cart.service';
export * from './error.service';
import { ErrorService } from './error.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './sKINETServer.service';
import { SKINETServerService } from './sKINETServer.service';
export const APIS = [AccountService, CartService, ErrorService, ProductsService, SKINETServerService];
